# Generated by Django 5.1 on 2024-09-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilePage', '0002_favoriterestaurant_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriterestaurant',
            name='distance',
        ),
    ]
