# Generated by Django 4.2.16 on 2024-10-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilePage", "0003_remove_favoriterestaurant_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoriterestaurant",
            name="distance",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
